### ISSUE TITLE
NSPhotoLibraryUsageDescription iOS10 issue

### ISSUE THREAD

**Issue by ojsglobal** [remoorejr/cordova-plugin-camera-with-exif#12]
As of today (have already had the app with this plugin approved), using the plugin with Phonegap Build, I received this error from Apple:

_This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data_

Obviously I'm not able to add a description key as I'm using PGB, and using the empty string in the past hasn't caused an issue, but it seems now it does.

Instead of having a blank description, could you not change it to a very broad, generic one, as it seems the blank one is no longer acceptable.

Cheers.

**Comment by remoorejr** [comment]
I added some default text for each entry.
