### ISSUE TITLE
Pluginfailed to install using Cordova CLI 5.4.1

### ISSUE THREAD

**Issue by lbhifi** [remoorejr/cordova-plugin-camera-with-exif#13]
Just what I was looking for, but unfortunately it won't install using Intel XDK.
I just get the error: "Error: Plugin cordova-plugin-camera-with-exif failed to install."

I'm using:

Cordova CLI 5.4.1

cordova-plugin-camera  v. 2.1.0

Minimum Android API 14
Target Android API 19

**Comment by remoorejr** [comment]
Try again, Android install should be fine. Problem was with iOS install with missing camera/library usage strings. They are now hard coded.

**Comment by lbhifi** [comment]
Sorry, my bad. I didn't mentions that it was actually the Android build that failed.
I tried the iOS build and it failed too, but left me with a more detailed log to examine. In this log I saw some  duplicate symbol like errors (I may not have the error text correct, it's from my memory), so I tried to remove my cordova-plugin-camera plugin and that did the trick :-)
