### ISSUE TITLE
iOS 10 no respose when pick a picture

### ISSUE THREAD

**Issue by claudioviola** [remoorejr/cordova-plugin-camera-with-exif#17]
Hello!
The plugin works fine for take-picture but doesn't works in pick-picture
I'm not receive any successCallback and errorCallback
Not happends anythings....

My options are these:
defaultOptions = { 
			quality : 60,
                       destinationType : Camera.DestinationType.FILE_URI,
                        sourceType : Camera.PictureSourceType.SAVEDPHOTOALBUM,
			allowEdit : false,
			encodingType: Camera.EncodingType.JPEG,
			popoverOptions: Camera.CameraPopoverOptions,
			saveToPhotoAlbum: false
};
The enviroment settings are:
Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0 
ios-sim version: 3.1.1 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002

Do you know any solution?
Thanks for your great job!

**Comment by jim0020** [comment]
It appears the plugin is not requesting permission to access the camera or photo library.
