### ISSUE TITLE
Some photos rotated 90deg

### ISSUE THREAD

**Issue by jamesl1001** [remoorejr/cordova-plugin-camera-with-exif#19]
I'm having an orientation issue where the orientation of some photos is not being corrected.

Thread here:
https://forum.ionicframework.com/t/camera-wrong-orientation-with-android/8583

I am wondering what version of cordova-plugin-camera this plugin is forked from and whether you keep it up-to-date?

**Comment by v-ken** [comment]
I'm having the same issue as well..

**Comment by v-ken** [comment]
@remoorejr @jamesl1001 Have you guys found a solution for this?

**Comment by jamesl1001** [comment]
@v-ken I haven't touched this issue in a long time I'm afraid! If I figure it out in the future I will update this thread.

**Comment by v-ken** [comment]
I've figured out the problem and created a pull request here

https://github.com/remoorejr/cordova-plugin-camera-with-exif/pull/37
