### ISSUE TITLE
Diff From cordova-plugin-camera

### ISSUE THREAD

**Issue by homerlex** [remoorejr/cordova-plugin-camera-with-exif#20]
Have you tried getting your changes merged into cordova-plugin-camera?  I don't understand why that project doesn't include exif info for Android (it does provide exif for iOS though).

I like what you have done but I fear your project will not grow with the changes that are getting applied to cordova-plugin-camera.

**Comment by jczaplew** [comment]
I would also love to see this merged into `cordova-plugin-camera`. Have you submitted a pull request, or would you be open to someone else submitting one on your behalf?
