### ISSUE TITLE
Can one override values for iOS plist strings in config.xml

### ISSUE THREAD

**Issue by jim0020** [remoorejr/cordova-plugin-camera-with-exif#22]
Is it possible to override the default values for NSCameraUsageDescription, NSPhotoLibraryUsageDescription, and NSLocationWhenInUseUsageDescription from plugin.xml in the app's config.xml?  In other words, can I set these values in config.xml?  If so, how?

For instance with the stock cordova-plugin-camera:

cordova plugin add cordova-plugin-camera --variable CAMERA_USAGE_DESCRIPTION="your usage message" --variable PHOTOLIBRARY_USAGE_DESCRIPTION="your usage message"

Thanks!

**Comment by remoorejr** [comment]
No, the strings are hard coded at this time.

Bob Moore
617-365-3231 - cell
@remoorejr
Sent via my iPhone 6
