### ISSUE TITLE
saveToPhotoAlbum: true does not save exif location data on ios

### ISSUE THREAD

**Issue by dylan-chong** [remoorejr/cordova-plugin-camera-with-exif#26]

**Comment by pugwonk** [comment]
I have a feeling this might be by design on iOS - I think it also strips out EXIF when you take a picture from the camera.

**Comment by dylan-chong** [comment]
If you take a picture using this plugin the exif location data is there. If you import from storage them, assuming the photo had exif location data, it in the image given by the plugin.

**Comment by austinhutchison** [comment]
This is weird behavior. The GPS data will be there when you take the photo, but if the photo is saved via `saveToPhotoAlbum` and you re-examine the exif data the GPS information is lost. (iOS 11.2.6, iPhone 6s)

**Comment by sathishkprakash** [comment]
hi remoorejr,

I am using this exif plugin and its working fine,But when i happen to fetch from library by keeping savetophotoalbum "true" ,it is not giving me the exif data.If i keep the savetophotoalbum "false",the images are saving in "DocumentDirectory" but not visible in albums of Iphone.Help needed
