### ISSUE TITLE
Cannot access photo got from Album

### ISSUE THREAD

**Issue by jfoclpf** [remoorejr/cordova-plugin-camera-with-exif#28]
The system allows access to Album.

I authorised the app to access albums and set in `options`

`sourceType: Camera.PictureSourceType.PHOTOLIBRARY`

But then the image is got from a directory from which the app cannot access or deal with

for example the returned image URL is 

`"/storage/emulated/0/DCIM/Camera/IMG_20180506_165850.jpg"`

but then I cannot copy this image nor deal with it. It seems I have no access to it. 

For example, when I copy the image, using 

```
//the album image uri is in imageUri
window.resolveLocalFileSystemURL(imageUri, function (sourceFile){
    window.resolveLocalFileSystemURL(cordova.file.externalApplicationStorageDirectory, function(destDir){                 
        sourceFile.copyTo(destDir, getFilenameFromURL(imageUri), function(){
            console.log("Successful Copy");
        });
    });                                                            
});
```

it can copy images from camera, but not from album

I already tried the three options

```
  Camera.DestinationType = {
      DATA_URL : 0,      // Return image as base64-encoded string
      FILE_URI : 1,      // Return image file URI
      NATIVE_URI : 2     // Return image native URI (e.g., assets-library:// on iOS or content:// on Android)
  };
```

and no success

**Comment by xCmac** [comment]
What platform are you having issues on?

this article shows an example of handling special permissions/ paths specifically for android (I'm assuming youre having issues on android)

https://devdactic.com/ionic-2-images/

**Comment by jfoclpf** [comment]
Yes, I am using Android, Apache Cordova `cordova-android": ^6.2.3` and  `cordova-plugin-camera-with-exif": "1.2.2`

I will check the article, thanks

**Comment by jfoclpf** [comment]
Hi, is there any article cordova specific?

The issue is that I came to your plugin because I needed the exif information and that works great, thanks, but I really think there is an issue here.

Because I can work very easily when the photo is gotten from `Camera.PictureSourceType.CAMERA` but I can't when they are stored in `Camera.PictureSourceType.PHOTOLIBRARY`

And I had _not_ such issue with the default `cordova-plugin-camera`

**Comment by jfoclpf** [comment]
I suppose I found the issue.

Does your app make the `window.requestFileSystem` ?

Just for the record, I got it working:
https://stackoverflow.com/a/50221986/1243247

**Comment by jfoclpf** [comment]
After many hours around, I finally got the issue. :)

You have a bug when collecting images from albums. In certain circumstances
the file name string is not preceded by

file://

which in android is mandatory

**Comment by jfoclpf** [comment]
Just for the sake of comprehensiveness

```
    var options = setOptions(Camera.PictureSourceType.PHOTOLIBRARY);
    
    navigator.camera.getPicture(function cameraSuccess(result) {

        // convert JSON string to JSON Object
        var thisResult = JSON.parse(result);

        var imageUri = thisResult.filename;        
        console.log("imageUri:" + imageUri);
    });

```
```
//camera plugin options
function setOptions(srcType) {
    var options = {
        // Some common settings are 20, 50, and 100
        quality: 50, //do not increase, otherwise the email plugin cannot attach photo due to photo file size
        destinationType: Camera.DestinationType.FILE_URI,
        // In this app, dynamically set the picture source, Camera or photo gallery
        sourceType: srcType,
        encodingType: Camera.EncodingType.JPEG,
        mediaType: Camera.MediaType.PICTURE,
        allowEdit: false,
        correctOrientation: true  //Corrects Android orientation quirks
    }
    return options;
}
```

and then I get in console

`imageUri:/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20180505-WA0004.jpg`

which is wrong in Android, it should be

`file:///storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20180505-WA0004.jpg`

cheers and thanks for the patience :)
