### ISSUE TITLE
Won't compile with cordova-ios v4.1.0

### ISSUE THREAD

**Issue by jim0020** [remoorejr/cordova-plugin-camera-with-exif#3]
CDVCamera.m is looking for #import <Cordova/NSArray+Comparisons.h> which doesn't seem to exist with cordova-ios v4.1.0.

As a workaround, I've moved the imports for Cordova/NSArray+Comparisons.h and Cordova/NSDictionary+Extensions.h into the #ifndef __CORDOVA_4_0_0
block just below.

**Comment by christianarielli** [comment]
I can confirm this behaviour.

**Comment by nskoro** [comment]
Hey I tried moving those imports, but it still won't build.


CompileC build/CameraPlus.build/Debug-iphonesimulator/CameraPlus.build/Objects-normal/i386/CDVCamera.o CameraPlus/Plugins/cordova-plugin-camera-with-exif/CDVCamera.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/nskoro/IonicCamera/platforms/ios/cordova/build-debug.xcconfig,-project,CameraPlus.xcodeproj,ARCHS=i386,-target,CameraPlus,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/nskoro/IonicCamera/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/nskoro/IonicCamera/platforms/ios/build/sharedpch
