### ISSUE TITLE
incorrect filename for Android Gallery image

### ISSUE THREAD

**Issue by dmccuskey** [remoorejr/cordova-plugin-camera-with-exif#32]
the plugin works for iOS Gallery and Camera and Android Camera, but not Android Gallery.

the returned filename for Android Gallery is missing the leading `file://`.

Android Camera: `file:///storage/emulated/0/Android/data/<app-name>/cache/1531849274218.jpg `
Android Gallery: `/storage/emulated/0/DCIM/Camera/IMG_20180714_145239.jpg`

Here is the code I added in my app to get around the issue:

```
const imageUri = (device.platform === Device.Platform.Android && sourceType === camera.PictureSourceType.PHOTOLIBRARY) ? `file://${filename}` : filename
```

Versions:

```
<plugin name="cordova-plugin-camera-with-exif" spec="^1.2.2" />
<engine name="android" spec="^6.3.0" />

Cordova: 8.0.0
```

thanks for developing this plugin

**Comment by dmccuskey** [comment]
hmm, seems like I changed a couple of parameters, and the plugin started working correctly. /shrug

I noticed that there are other bug reports with similar behavior.

here is my code now, for the cases when it does work on Android:

```
let imageUri = filename
 if (device.platform === Device.Platform.Android) {
     imageUri = filename.indexOf('file://') === -1 ? `file://${filename}` : filename
}
```

**Comment by v-ken** [comment]
@dmccuskey Are you able to display the selected image from the Android Gallery? I get this error message in the console: `Not allowed to load local resource: file:///storage/emulated/0/Download/58367406115c0cbf161d03a09d75dcd71533904900553560699.jpg`

**Comment by v-ken** [comment]
Argh! Just run it without live reload and it works:
https://stackoverflow.com/a/45865237/2491738
