### ISSUE TITLE
How do we install this in an ionic 3 app?

### ISSUE THREAD

**Issue by v-ken** [remoorejr/cordova-plugin-camera-with-exif#34]
Since there isn't an @ionic-native/camera-with-exif version of this, how do we install this in an ionic 3 app?

**Comment by remoorejr** [comment]
Unknown, I don't use Ionic. Anyone ?

**Comment by v-ken** [comment]
I found out how to do it:

1. Remove cordova-plugin-camera if it was previously installed

```
$ npm uninstall --save @ionic-native/camera
$ ionic cordova plugin remove cordova-plugin-camera
```

2. Ensure that both `cordova-plugin-camera` and `@ionic-native/camera` are removed from `package.json`.

3. Remove any references to the old `Camera` object from all your source files.

4. Install the `cordova-plugin-camera-with-exif` plugin
```
$ cordova plugin add cordova-plugin-camera-with-exif
```

5. Use it as follow:
```javascript
// Declare the navigator instance
// The plugin will be injected into this instance
declare var navigator: any;

// Using the camera
const cameraOptions = {
      quality: 40,
      destinationType: destinationType,
      encodingType: navigator.camera.EncodingType.JPEG,
      mediaType: mediaType,
      sourceType: sourceType,
      correctOrientation: true
    }

launchCamera() {
    function onSuccess(result) {
       // convert JSON string to JSON Object
       var thisResult = JSON.parse(result);

       // convert json_metadata JSON string to JSON Object
       var metadata = JSON.parse(thisResult.json_metadata);
    }

    function onFail(message) {
        alert('Failed because: ' + message);
    }

    navigator.camera.getPicture(onSuccess, onFail, cameraOptions);
}
```

6. Remove and re-add platforms

```
$ ionic cordova platform remove ios
$ ionic cordova platform add ios
```
7. Build target

```
$ ionic cordova build ios
```

**Comment by remoorejr** [comment]
Thanks!

**Comment by sathishkprakash** [comment]
hi remoorejr,

I am using this exif plugin and its working fine,But when i happen to fetch from library by keeping savetophotoalbum "true" ,it is not giving me the exif data.If i keep the savetophotoalbum "false",the images are saving in "DocumentDirectory" but not visible in albums of Iphone.Help needed
