### ISSUE TITLE
Best method to compress image?

### ISSUE THREAD

**Issue by v-ken** [remoorejr/cordova-plugin-camera-with-exif#35]
I understand the following from the docs:

> NOTE: Photo resolution on newer devices is quite good. Photos selected from the device's gallery are not downscaled to a lower quality, even if a quality parameter is specified. 

I was wondering what the best way is to compress the jpeg after the image is selected from the gallery?

I've tried https://ionicframework.com/docs/native/image-resizer/ but it relies on `cordova-plugin-camera` which cannot be used together with `cordova-plugin-camera-with-exif`.

**Comment by dmccuskey** [comment]
@v-ken perhaps you could use another library like this one: https://github.com/nodeca/pica

**Comment by v-ken** [comment]
@dmccuskey Thanks for the suggestion. I ended up scaling the image by setting a smaller image size than the original.
