### ISSUE TITLE
Gson missing after replacing stock plugin

### ISSUE THREAD

**Issue by ddsky** [remoorejr/cordova-plugin-camera-with-exif#36]
After removing the stock camera plugin and adding cordova-plugin-camera-with-exif I get a lot of error messages during compile, all of them are similar to the first one which is:

```
...platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:47: error: package com.google.gson does not exist
import com.google.gson.Gson;
```

Does anyone know what is going wrong here? I already tried removing android platform and adding it back but still get this error.

**Comment by v-ken** [comment]
I'm getting the same error. We can't be the only ones?

**Comment by v-ken** [comment]
Seems to work when you add 
```
implementation 'com.google.code.gson:gson:2.8.2'
```
in the gradle file
