### ISSUE TITLE
Missing GPS info

### ISSUE THREAD

**Issue by vlinde** [remoorejr/cordova-plugin-camera-with-exif#45]
Hi,
I have a small issue when I try to get the GPS info from the camera.
Sometimes I get the GPS info, sometimes not and I don't know exactly why this is happening.
I added some logs in plugin and the problem appeared directly after the Exif info are parsed.

 I use the following options:
```
{    
   sourceType: navigator.camera.PictureSourceType.CAMERA,
    destinationType: navigator.camera.DestinationType.FILE_URI,
    quality: 92,
    encodingType: navigator.camera.EncodingType.JPEG,
    correctOrientation: true,
    saveToPhotoAlbum: false
}
```
The issue appeared randomly on: Samsung Galaxy Note 8, Xiaomi mi 5 and Honor 8x.

**Comment by baldodavi** [comment]
Same issue here, someone have found a solution or a workaround?
Saving images on devices shown that also saved images not contains gps metadata.

`{
	"aperture": "2.0",
	"datetime": "2019:09:17 15:51:55",
	"exposureTime": "0.120003",
	"flash": "0",
	"focalLength": "3500/1000",
	"gpsAltitude": null,
	"gpsAltitudeRef": null,
	"gpsDateStamp": null,
	"gpsLatitude": null,
	"gpsLatitudeRef": null,
	"gpsLongitude": null,
	"gpsLongitudeRef": null,
	"gpsProcessingMethod": null,
	"gpsTimestamp": null,
	"iso": "807",
	"make": "vernee",
	"model": "MIX 2",
	"orientation": "0",
	"whiteBalance": "0"
}`

**Comment by vlinde** [comment]
Hi @baldodavi,
Here is the fix: https://github.com/vlinde/cordova-plugin-camera-with-exif/commit/1cfec1e4874533220b394d5f1dc6f372a40aad92

I think you should check the other commits too.

**Comment by baldodavi** [comment]
Thanks a lot @vlinde

**Comment by oDresSystems** [comment]
Hi, I am still having the gps null problema, I tested in a Ionic app and GPS is not getting any data, How can i fix this? any ideas?

**Comment by SumeetHindinkeri** [comment]
Hi @vlinde , 
Thanks for the fix but I am not getting gps data when the sourceType is PHOTOLIBRARY for ios only.
