### ISSUE TITLE
image from gallery taken on portrait mode is returned as landscape after ios 13 fixes

### ISSUE THREAD

**Issue by gezn** [remoorejr/cordova-plugin-camera-with-exif#48]
**steps to reproduce.**

ask the library for an image, with "orientationCorrection"  choose  "gallery" and choose an image taken before on portrait mode.

**result** 

the image will be returned on landscape mode

**expected result**

the image should return on portrait mode

**Comment by formigarafa** [comment]
Confirming what was said above:

When a Photo is loaded from IOS Gallery, File sent has the image reoriented but the exif information for "orientation" remains as the original file from the gallery.

This means the file sent is now in an inconsistent orientation state. (BTW, `correctOrientation` param has no effect on such files)
