### ISSUE TITLE
GPS Latitude and Longitude Info returning null in MetaData

### ISSUE THREAD

**Issue by prasadadvs** [remoorejr/cordova-plugin-camera-with-exif#50]
Hi,

The Android App Build using the latest code, returns a null value for the GPS Latitude and Longitude.  Have tested it on Galaxy and Asus devices running Android version 9. No luck
Is there a workaround to fix this issue. 
Thanks,

Regards,
Prasad

**Comment by oDresSystems** [comment]
I am having the same problem and I have to fix it really soon, so any suggestion?

**Comment by robinparadise** [comment]
Nobody have a clue about this?

**Comment by bojanbizjak** [comment]
Same problem. Android 10+

**Comment by remoorejr** [comment]
This should be resolved as of v 1.4.2.
