### ISSUE TITLE
When using gallery - Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)"

### ISSUE THREAD

**Issue by helenburns** [remoorejr/cordova-plugin-camera-with-exif#54]
I've been using this plugin for a while with an app that requires EXIF data when taking photos with the camera and choosing them from the library. It has been the perfect solution.

It would seem with one of the recent iOS 14 Apple updates (this app is only on iOS at present) the ability to choose a photo from any gallery or album results in this error being thrown: `Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)"`. It definitely used to work!

I have all the right privacy and location preferences set and they are showing up correctly in XCode. It DOES appear to work on a simulator though. I think it may be related to the privacy settings as, when using for the first time on the simulator, it requests permission AFTER allowing you to choose from the gallery, and then works. This seems wrong to me. It never works on a device any more (mine being an iPhone 8 running 14.4). It simply throws this error.

Any help/guidance appreciated as I really rely on this plugin for this app. Thanks.

**Comment by remoorejr** [comment]
I'm unable to duplicate this.
