### ISSUE TITLE
Empty json_metadata on Android 10(Redmi 7)

### ISSUE THREAD

**Issue by Modem-i4** [remoorejr/cordova-plugin-camera-with-exif#55]
I'm getting empty json_metadata. I've tried both "URL" and "URI" destinations but nothing changes. 
The JSON I get looks like this:
`{"filename":"content://com.android.providers.media.documents/document/image%3A504578","json_metadata":""}`

I've tested this also on Redmi 4X with Android 7.1.2 and there everything is fine

**Comment by remoorejr** [comment]
The problem is a permissions issue with the newer versions of Android. I'm working on a resolution and have a test case that is working correctly. I'll update the plugin after some further development/testing.

**Comment by Modem-i4** [comment]
Thanks for your hard work! 
Your plugin is really useful and I'm sure you will help a lot of people with updating it
